name: Vehicle Test Action

on: 
  push: 
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      name: Do something
      - uses: actions/checkout@v2

      - name: Display JSON
        with: './'
        run: echo "hello"