name: Vehicle Test Action

on: 
  push: master

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Display JSON
        with: './'
      - run: echo "hello"